# Generated by Django 5.2.15 on 2026-06-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanilhaRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_venda', models.DateField(blank=True, null=True)),
                ('contador_parceiro', models.CharField(blank=True, max_length=255)),
                ('contador_contabilidade', models.CharField(blank=True, max_length=255)),
                ('telefone1', models.CharField(blank=True, max_length=50)),
                ('cliente', models.CharField(blank=True, max_length=255)),
                ('cpf_cnpj', models.CharField(blank=True, max_length=64)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone2', models.CharField(blank=True, max_length=50)),
                ('tipo_certificado', models.CharField(blank=True, max_length=255)),
                ('valor_venda', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('percentual_comissao', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('valor_comissao', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('pago_comissao', models.BooleanField(default=False)),
                ('chave_pix', models.CharField(blank=True, max_length=255)),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('pago_venda', models.BooleanField(default=False)),
                ('forma_pagamento', models.CharField(blank=True, max_length=255)),
                ('banco', models.CharField(blank=True, max_length=255)),
                ('certificado_feito', models.CharField(blank=True, max_length=255)),
                ('venda', models.CharField(blank=True, max_length=255)),
                ('custo_certificado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('valor_liquido', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
