# Generated by Django 5.2.15 on 2026-06-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('valor_comissao', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('comissao_paga', models.BooleanField(default=False)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
