# Generated by Django on 2026-07-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Gestor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('data', models.JSONField(default=dict)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
