# Generated by Django 5.2.15 on 2026-07-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Gestor', '0002_add_appstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_ref', models.CharField(blank=True, db_index=True, max_length=128)),
                ('nome_cliente', models.CharField(blank=True, max_length=255)),
                ('arquivo', models.FileField(upload_to='documentos/%Y/%m/%d/')),
                ('observacao', models.TextField(blank=True)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PagamentoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_ref', models.CharField(blank=True, db_index=True, max_length=128)),
                ('nome_cliente', models.CharField(blank=True, max_length=255)),
                ('email_cliente', models.EmailField(blank=True, max_length=254)),
                ('metodo', models.CharField(choices=[('pix', 'Pix'), ('bolbradesco', 'Boleto')], default='pix', max_length=32)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descricao', models.CharField(max_length=255)),
                ('gateway', models.CharField(default='mercadopago', max_length=32)),
                ('gateway_payment_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Recusado'), ('cancelled', 'Cancelado')], default='pending', max_length=32)),
                ('qr_code_base64', models.TextField(blank=True)),
                ('qr_code_copia_cola', models.TextField(blank=True)),
                ('boleto_url', models.URLField(blank=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
