# Generated by Django 5.2.15 on 2026-07-19

import core.app_Gestor.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_planilharegistro'),
        ('app_Gestor', '0003_documentocliente_pagamentocliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentocliente',
            name='registro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='app.planilharegistro'),
        ),
        migrations.AlterField(
            model_name='documentocliente',
            name='arquivo',
            field=models.FileField(upload_to=core.app_Gestor.models.caminho_documento_cliente),
        ),
        migrations.AddField(
            model_name='documentocliente',
            name='nome_original',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='documentocliente',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('rg_cnh', 'RG/CNH'), ('contrato_social', 'Contrato Social'), ('comprovante_residencia', 'Comprovante de Residência'), ('foto_selfie', 'Foto/Selfie'), ('outro', 'Outro')], default='outro', max_length=32),
        ),
        migrations.AddField(
            model_name='documentocliente',
            name='tamanho_bytes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]